apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aether-master
  namespace: aether
spec:
  project: default
  source:
    repoURL: https://github.com/victormongi/k8s-deployment
    targetRevision: HEAD
    path: aether-master
  destination:
    server: https://kubernetes.default.svc
    namespace: aether
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
