apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-elysia-victor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.rsupkandou.id/devops/victor-elysia.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-victor-elysia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
