apiVersion: apps/v1
kind: Deployment
metadata:
  name: victor-deployment
  labels:
    app: victor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: victor
  template:
    metadata:
      labels:
        app: victor
    spec:
      containers:
      - name: victor-elysia
        image: victormongi/elysia:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: secret-coba
              key: nama
        - name: BUILD_NUMBER
          valueFrom:
            secretKeyRef:
              name: secret-coba
              key: build_number
